---
- name: restart the machine
  shell: sleep 2 && shutdown -r now "Server is rebooting"
  async: 1
  poll: 0
  ignore_errors: true

- name: waiting for server
  wait_for:
     host: "{{ inventory_hostname }}"
     state: started
     delay: 10
     timeout: 300
     port: 22
  delegate_to: localhost

- name: checking if any service has failed
  shell: systemctl --all --fail | grep failed > output.txt
  ignore_errors: True

- stat:
    path: output.txt
  register: file

- fail:
    msg: "File has some value in it, so something failed"
  when: file.stat.size != 0
